spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: postgres
        password: password123

    jpa:
        hibernate:
            ddl-auto: update

    main:
        allow-circular-references: true